name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: read # to fetch code

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: npm install
      - run: npm run build

      - name: Run unit tests
        run: npm run test
